### ISSUE TITLE
Remover os arquivos swp do vim inseridos pelo leandro. E removê-los no .gitignore

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco_laravel#50]

**Comment by leandroramos** [comment]
Não entendi. É para remover os arquivos e tbm remover a entrada no .gitignore?

**Comment by thiagogomesverissimo** [comment]
Criar uma regra no gitignore para não ocorrer mais isso:

`*.swp`

**Comment by leandroramos** [comment]
Eu mandei essa alteração, mas deve ter sido numa PR que eu mesmo apaguei haha

**Comment by girol** [comment]
Solved in #68
